#!/bin/sh

### BEGIN INIT INFO
# Provides:             usc
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    USC Node
### END INIT INFO

. /lib/lsb/init-functions

check_status() {
  s=`ps -C 'java' -o pid h`
  if [ $s ] ; then
    return $s
  fi
  return 10
}

start() {
  check_status
  pid=$?
  if [ $pid -ne 10 ] ; then
    echo "The application is already started"
    exit 1
  fi
  echo -n "Starting application: "
/bin/su - usc -s /bin/bash -c "<JAVA_PATH> -Dlogback.configurationFile='/etc/usc/logback.xml' -cp /usr/share/usc/usc.jar co.usc.Start > /dev/null 2>&1 &"
  echo "OK"
}

stop() {
  check_status
  pid=$?
  if [ $pid -eq 0 ] ; then
    echo "Application is already stopped"
    exit 1
  fi
  echo -n "Stopping application: "
  kill -15 $pid &
  echo "OK"
}

status() {
  check_status
  if [ $? -ne 10 ] ; then
    echo "Application is started"
  else
    echo "Application is stopped"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|force-reload|reload}"
    exit 1
esac

exit 0
